html_sheets/Nasso/1162.html: (<class 'sefaria.system.exceptions.InputError'>, InputError(u'Could not find title in reference: Gur Aryeh on Numbers',))
Traceback (most recent call last):
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Data/sources/Nechama/main.py", line 1034, in bs4_reader
    sheet.create_sheetsources_from_objsource()
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Data/sources/Nechama/main.py", line 62, in create_sheetsources_from_objsource
    seg_sheet_source = segment.create_source()
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Data/sources/Nechama/segments.py", line 105, in create_source
    self.ref = Ref(" ".join(self.ref.split()[0:-1])).he_normal()
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Project/sefaria/model/text.py", line 1954, in __call__
    result = super(RefCacheType, cls).__call__(*args, **kwargs)
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Project/sefaria/model/text.py", line 2033, in __init__
    self.__init_tref()
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Project/sefaria/model/text.py", line 2170, in __init_tref
    raise InputError(u"Could not find title in reference: {}".format(self.tref))
InputError: Could not find title in reference: Gur Aryeh on Numbers


html_sheets/Nasso/530.html: (<class 'sefaria.system.exceptions.InputError'>, InputError(u'Could not find title in reference: Gur Aryeh on Numbers',))
Traceback (most recent call last):
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Data/sources/Nechama/main.py", line 1034, in bs4_reader
    sheet.create_sheetsources_from_objsource()
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Data/sources/Nechama/main.py", line 62, in create_sheetsources_from_objsource
    seg_sheet_source = segment.create_source()
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Data/sources/Nechama/segments.py", line 105, in create_source
    self.ref = Ref(" ".join(self.ref.split()[0:-1])).he_normal()
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Project/sefaria/model/text.py", line 1954, in __call__
    result = super(RefCacheType, cls).__call__(*args, **kwargs)
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Project/sefaria/model/text.py", line 2033, in __init__
    self.__init_tref()
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Project/sefaria/model/text.py", line 2170, in __init_tref
    raise InputError(u"Could not find title in reference: {}".format(self.tref))
InputError: Could not find title in reference: Gur Aryeh on Numbers


html_sheets/Nasso/1266.html: (<type 'exceptions.IndexError'>, IndexError('list index out of range',))
Traceback (most recent call last):
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Data/sources/Nechama/main.py", line 1033, in bs4_reader
    sheet.parse_as_text()
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Data/sources/Nechama/main.py", line 176, in parse_as_text
    section.add_segments(section.soupObj)
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Data/sources/Nechama/main.py", line 215, in add_segments
    self.classify_segments(soup_segments) #self.segment_objects += self.classify_segments(soup_segments)
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Data/sources/Nechama/main.py", line 280, in classify_segments
    sheet_segment = self.classify(segment, i, soup_segments)
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Data/sources/Nechama/main.py", line 316, in classify
    current_source = [x for x in self.segment_objects if (isinstance(x, Source) and x.current)][-1]
IndexError: list index out of range


html_sheets/Nasso/1412.html: (<type 'exceptions.IndexError'>, IndexError('list index out of range',))
Traceback (most recent call last):
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Data/sources/Nechama/main.py", line 1033, in bs4_reader
    sheet.parse_as_text()
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Data/sources/Nechama/main.py", line 176, in parse_as_text
    section.add_segments(section.soupObj)
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Data/sources/Nechama/main.py", line 215, in add_segments
    self.classify_segments(soup_segments) #self.segment_objects += self.classify_segments(soup_segments)
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Data/sources/Nechama/main.py", line 280, in classify_segments
    sheet_segment = self.classify(segment, i, soup_segments)
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Data/sources/Nechama/main.py", line 316, in classify
    current_source = [x for x in self.segment_objects if (isinstance(x, Source) and x.current)][-1]
IndexError: list index out of range


html_sheets/Nasso/187.html: (<class 'sefaria.system.exceptions.InputError'>, InputError(u'Could not find title in reference: Gur Aryeh on Numbers',))
Traceback (most recent call last):
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Data/sources/Nechama/main.py", line 1034, in bs4_reader
    sheet.create_sheetsources_from_objsource()
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Data/sources/Nechama/main.py", line 62, in create_sheetsources_from_objsource
    seg_sheet_source = segment.create_source()
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Data/sources/Nechama/segments.py", line 105, in create_source
    self.ref = Ref(" ".join(self.ref.split()[0:-1])).he_normal()
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Project/sefaria/model/text.py", line 1954, in __call__
    result = super(RefCacheType, cls).__call__(*args, **kwargs)
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Project/sefaria/model/text.py", line 2033, in __init__
    self.__init_tref()
  File "/Users/stevenkaplan/Documents/Sefaria/Sefaria-Project/sefaria/model/text.py", line 2170, in __init_tref
    raise InputError(u"Could not find title in reference: {}".format(self.tref))
InputError: Could not find title in reference: Gur Aryeh on Numbers


